/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devops.proto

package protos;

public final class DevopsOuterClass {
  private DevopsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SecretOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.Secret)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string enrollId = 1;</code>
     */
    String getEnrollId();
    /**
     * <code>optional string enrollId = 1;</code>
     */
    com.google.protobuf.ByteString
        getEnrollIdBytes();

    /**
     * <code>optional string enrollSecret = 2;</code>
     */
    String getEnrollSecret();
    /**
     * <code>optional string enrollSecret = 2;</code>
     */
    com.google.protobuf.ByteString
        getEnrollSecretBytes();
  }
  /**
   * Protobuf type {@code protos.Secret}
   *
   * <pre>
   * Secret is a temporary object to establish security with the Devops.
   * A better solution using certificate will be introduced later
   * </pre>
   */
  public  static final class Secret extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.Secret)
      SecretOrBuilder {
    // Use Secret.newBuilder() to construct.
    private Secret(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Secret() {
      enrollId_ = "";
      enrollSecret_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Secret(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              enrollId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              enrollSecret_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.DevopsOuterClass.internal_static_protos_Secret_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.DevopsOuterClass.internal_static_protos_Secret_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.DevopsOuterClass.Secret.class, protos.DevopsOuterClass.Secret.Builder.class);
    }

    public static final int ENROLLID_FIELD_NUMBER = 1;
    private volatile Object enrollId_;
    /**
     * <code>optional string enrollId = 1;</code>
     */
    public String getEnrollId() {
      Object ref = enrollId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        enrollId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string enrollId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEnrollIdBytes() {
      Object ref = enrollId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        enrollId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENROLLSECRET_FIELD_NUMBER = 2;
    private volatile Object enrollSecret_;
    /**
     * <code>optional string enrollSecret = 2;</code>
     */
    public String getEnrollSecret() {
      Object ref = enrollSecret_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        enrollSecret_ = s;
        return s;
      }
    }
    /**
     * <code>optional string enrollSecret = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEnrollSecretBytes() {
      Object ref = enrollSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        enrollSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEnrollIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, enrollId_);
      }
      if (!getEnrollSecretBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, enrollSecret_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEnrollIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, enrollId_);
      }
      if (!getEnrollSecretBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, enrollSecret_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protos.DevopsOuterClass.Secret parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protos.DevopsOuterClass.Secret parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protos.DevopsOuterClass.Secret parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protos.DevopsOuterClass.Secret parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.DevopsOuterClass.Secret prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.Secret}
     *
     * <pre>
     * Secret is a temporary object to establish security with the Devops.
     * A better solution using certificate will be introduced later
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.Secret)
        protos.DevopsOuterClass.SecretOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.DevopsOuterClass.internal_static_protos_Secret_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.DevopsOuterClass.internal_static_protos_Secret_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.DevopsOuterClass.Secret.class, protos.DevopsOuterClass.Secret.Builder.class);
      }

      // Construct using protos.DevopsOuterClass.Secret.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        enrollId_ = "";

        enrollSecret_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.DevopsOuterClass.internal_static_protos_Secret_descriptor;
      }

      public protos.DevopsOuterClass.Secret getDefaultInstanceForType() {
        return protos.DevopsOuterClass.Secret.getDefaultInstance();
      }

      public protos.DevopsOuterClass.Secret build() {
        protos.DevopsOuterClass.Secret result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.DevopsOuterClass.Secret buildPartial() {
        protos.DevopsOuterClass.Secret result = new protos.DevopsOuterClass.Secret(this);
        result.enrollId_ = enrollId_;
        result.enrollSecret_ = enrollSecret_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.DevopsOuterClass.Secret) {
          return mergeFrom((protos.DevopsOuterClass.Secret)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.DevopsOuterClass.Secret other) {
        if (other == protos.DevopsOuterClass.Secret.getDefaultInstance()) return this;
        if (!other.getEnrollId().isEmpty()) {
          enrollId_ = other.enrollId_;
          onChanged();
        }
        if (!other.getEnrollSecret().isEmpty()) {
          enrollSecret_ = other.enrollSecret_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.DevopsOuterClass.Secret parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.DevopsOuterClass.Secret) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object enrollId_ = "";
      /**
       * <code>optional string enrollId = 1;</code>
       */
      public String getEnrollId() {
        Object ref = enrollId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          enrollId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string enrollId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEnrollIdBytes() {
        Object ref = enrollId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          enrollId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string enrollId = 1;</code>
       */
      public Builder setEnrollId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        enrollId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string enrollId = 1;</code>
       */
      public Builder clearEnrollId() {
        
        enrollId_ = getDefaultInstance().getEnrollId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string enrollId = 1;</code>
       */
      public Builder setEnrollIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        enrollId_ = value;
        onChanged();
        return this;
      }

      private Object enrollSecret_ = "";
      /**
       * <code>optional string enrollSecret = 2;</code>
       */
      public String getEnrollSecret() {
        Object ref = enrollSecret_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          enrollSecret_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string enrollSecret = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEnrollSecretBytes() {
        Object ref = enrollSecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          enrollSecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string enrollSecret = 2;</code>
       */
      public Builder setEnrollSecret(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        enrollSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string enrollSecret = 2;</code>
       */
      public Builder clearEnrollSecret() {
        
        enrollSecret_ = getDefaultInstance().getEnrollSecret();
        onChanged();
        return this;
      }
      /**
       * <code>optional string enrollSecret = 2;</code>
       */
      public Builder setEnrollSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        enrollSecret_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.Secret)
    }

    // @@protoc_insertion_point(class_scope:protos.Secret)
    private static final protos.DevopsOuterClass.Secret DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.DevopsOuterClass.Secret();
    }

    public static protos.DevopsOuterClass.Secret getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Secret>
        PARSER = new com.google.protobuf.AbstractParser<Secret>() {
      public Secret parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Secret(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Secret> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Secret> getParserForType() {
      return PARSER;
    }

    public protos.DevopsOuterClass.Secret getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.BuildResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
     */
    protos.DevopsOuterClass.BuildResult.StatusCode getStatus();

    /**
     * <code>optional string msg = 2;</code>
     */
    String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
     */
    boolean hasDeploymentSpec();
    /**
     * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
     */
    protos.Chaincode.ChaincodeDeploymentSpec getDeploymentSpec();
    /**
     * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
     */
    protos.Chaincode.ChaincodeDeploymentSpecOrBuilder getDeploymentSpecOrBuilder();
  }
  /**
   * Protobuf type {@code protos.BuildResult}
   */
  public  static final class BuildResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protos.BuildResult)
      BuildResultOrBuilder {
    // Use BuildResult.newBuilder() to construct.
    private BuildResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BuildResult() {
      status_ = 0;
      msg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BuildResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 26: {
              protos.Chaincode.ChaincodeDeploymentSpec.Builder subBuilder = null;
              if (deploymentSpec_ != null) {
                subBuilder = deploymentSpec_.toBuilder();
              }
              deploymentSpec_ = input.readMessage(protos.Chaincode.ChaincodeDeploymentSpec.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deploymentSpec_);
                deploymentSpec_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.DevopsOuterClass.internal_static_protos_BuildResult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.DevopsOuterClass.internal_static_protos_BuildResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.DevopsOuterClass.BuildResult.class, protos.DevopsOuterClass.BuildResult.Builder.class);
    }

    /**
     * Protobuf enum {@code protos.BuildResult.StatusCode}
     */
    public enum StatusCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNDEFINED = 0;</code>
       */
      UNDEFINED(0, 0),
      /**
       * <code>SUCCESS = 1;</code>
       */
      SUCCESS(1, 1),
      /**
       * <code>FAILURE = 2;</code>
       */
      FAILURE(2, 2),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>UNDEFINED = 0;</code>
       */
      public static final int UNDEFINED_VALUE = 0;
      /**
       * <code>SUCCESS = 1;</code>
       */
      public static final int SUCCESS_VALUE = 1;
      /**
       * <code>FAILURE = 2;</code>
       */
      public static final int FAILURE_VALUE = 2;


      public final int getNumber() {
        if (index == -1) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static StatusCode valueOf(int value) {
        switch (value) {
          case 0: return UNDEFINED;
          case 1: return SUCCESS;
          case 2: return FAILURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StatusCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
              public StatusCode findValueByNumber(int number) {
                return StatusCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protos.DevopsOuterClass.BuildResult.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusCode[] VALUES = values();

      public static StatusCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StatusCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protos.BuildResult.StatusCode)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
     */
    public protos.DevopsOuterClass.BuildResult.StatusCode getStatus() {
      protos.DevopsOuterClass.BuildResult.StatusCode result = protos.DevopsOuterClass.BuildResult.StatusCode.valueOf(status_);
      return result == null ? protos.DevopsOuterClass.BuildResult.StatusCode.UNRECOGNIZED : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPLOYMENTSPEC_FIELD_NUMBER = 3;
    private protos.Chaincode.ChaincodeDeploymentSpec deploymentSpec_;
    /**
     * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
     */
    public boolean hasDeploymentSpec() {
      return deploymentSpec_ != null;
    }
    /**
     * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
     */
    public protos.Chaincode.ChaincodeDeploymentSpec getDeploymentSpec() {
      return deploymentSpec_ == null ? protos.Chaincode.ChaincodeDeploymentSpec.getDefaultInstance() : deploymentSpec_;
    }
    /**
     * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
     */
    public protos.Chaincode.ChaincodeDeploymentSpecOrBuilder getDeploymentSpecOrBuilder() {
      return getDeploymentSpec();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != protos.DevopsOuterClass.BuildResult.StatusCode.UNDEFINED.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, msg_);
      }
      if (deploymentSpec_ != null) {
        output.writeMessage(3, getDeploymentSpec());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != protos.DevopsOuterClass.BuildResult.StatusCode.UNDEFINED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, msg_);
      }
      if (deploymentSpec_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDeploymentSpec());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static protos.DevopsOuterClass.BuildResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protos.DevopsOuterClass.BuildResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protos.DevopsOuterClass.BuildResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protos.DevopsOuterClass.BuildResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.DevopsOuterClass.BuildResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protos.BuildResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.BuildResult)
        protos.DevopsOuterClass.BuildResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.DevopsOuterClass.internal_static_protos_BuildResult_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.DevopsOuterClass.internal_static_protos_BuildResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.DevopsOuterClass.BuildResult.class, protos.DevopsOuterClass.BuildResult.Builder.class);
      }

      // Construct using protos.DevopsOuterClass.BuildResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        msg_ = "";

        if (deploymentSpecBuilder_ == null) {
          deploymentSpec_ = null;
        } else {
          deploymentSpec_ = null;
          deploymentSpecBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.DevopsOuterClass.internal_static_protos_BuildResult_descriptor;
      }

      public protos.DevopsOuterClass.BuildResult getDefaultInstanceForType() {
        return protos.DevopsOuterClass.BuildResult.getDefaultInstance();
      }

      public protos.DevopsOuterClass.BuildResult build() {
        protos.DevopsOuterClass.BuildResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.DevopsOuterClass.BuildResult buildPartial() {
        protos.DevopsOuterClass.BuildResult result = new protos.DevopsOuterClass.BuildResult(this);
        result.status_ = status_;
        result.msg_ = msg_;
        if (deploymentSpecBuilder_ == null) {
          result.deploymentSpec_ = deploymentSpec_;
        } else {
          result.deploymentSpec_ = deploymentSpecBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.DevopsOuterClass.BuildResult) {
          return mergeFrom((protos.DevopsOuterClass.BuildResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.DevopsOuterClass.BuildResult other) {
        if (other == protos.DevopsOuterClass.BuildResult.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasDeploymentSpec()) {
          mergeDeploymentSpec(other.getDeploymentSpec());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.DevopsOuterClass.BuildResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.DevopsOuterClass.BuildResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
       */
      public protos.DevopsOuterClass.BuildResult.StatusCode getStatus() {
        protos.DevopsOuterClass.BuildResult.StatusCode result = protos.DevopsOuterClass.BuildResult.StatusCode.valueOf(status_);
        return result == null ? protos.DevopsOuterClass.BuildResult.StatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
       */
      public Builder setStatus(protos.DevopsOuterClass.BuildResult.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .protos.BuildResult.StatusCode status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private protos.Chaincode.ChaincodeDeploymentSpec deploymentSpec_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          protos.Chaincode.ChaincodeDeploymentSpec, protos.Chaincode.ChaincodeDeploymentSpec.Builder, protos.Chaincode.ChaincodeDeploymentSpecOrBuilder> deploymentSpecBuilder_;
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public boolean hasDeploymentSpec() {
        return deploymentSpecBuilder_ != null || deploymentSpec_ != null;
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public protos.Chaincode.ChaincodeDeploymentSpec getDeploymentSpec() {
        if (deploymentSpecBuilder_ == null) {
          return deploymentSpec_ == null ? protos.Chaincode.ChaincodeDeploymentSpec.getDefaultInstance() : deploymentSpec_;
        } else {
          return deploymentSpecBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public Builder setDeploymentSpec(protos.Chaincode.ChaincodeDeploymentSpec value) {
        if (deploymentSpecBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deploymentSpec_ = value;
          onChanged();
        } else {
          deploymentSpecBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public Builder setDeploymentSpec(
          protos.Chaincode.ChaincodeDeploymentSpec.Builder builderForValue) {
        if (deploymentSpecBuilder_ == null) {
          deploymentSpec_ = builderForValue.build();
          onChanged();
        } else {
          deploymentSpecBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public Builder mergeDeploymentSpec(protos.Chaincode.ChaincodeDeploymentSpec value) {
        if (deploymentSpecBuilder_ == null) {
          if (deploymentSpec_ != null) {
            deploymentSpec_ =
              protos.Chaincode.ChaincodeDeploymentSpec.newBuilder(deploymentSpec_).mergeFrom(value).buildPartial();
          } else {
            deploymentSpec_ = value;
          }
          onChanged();
        } else {
          deploymentSpecBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public Builder clearDeploymentSpec() {
        if (deploymentSpecBuilder_ == null) {
          deploymentSpec_ = null;
          onChanged();
        } else {
          deploymentSpec_ = null;
          deploymentSpecBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public protos.Chaincode.ChaincodeDeploymentSpec.Builder getDeploymentSpecBuilder() {
        
        onChanged();
        return getDeploymentSpecFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      public protos.Chaincode.ChaincodeDeploymentSpecOrBuilder getDeploymentSpecOrBuilder() {
        if (deploymentSpecBuilder_ != null) {
          return deploymentSpecBuilder_.getMessageOrBuilder();
        } else {
          return deploymentSpec_ == null ?
              protos.Chaincode.ChaincodeDeploymentSpec.getDefaultInstance() : deploymentSpec_;
        }
      }
      /**
       * <code>optional .protos.ChaincodeDeploymentSpec deploymentSpec = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protos.Chaincode.ChaincodeDeploymentSpec, protos.Chaincode.ChaincodeDeploymentSpec.Builder, protos.Chaincode.ChaincodeDeploymentSpecOrBuilder> 
          getDeploymentSpecFieldBuilder() {
        if (deploymentSpecBuilder_ == null) {
          deploymentSpecBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protos.Chaincode.ChaincodeDeploymentSpec, protos.Chaincode.ChaincodeDeploymentSpec.Builder, protos.Chaincode.ChaincodeDeploymentSpecOrBuilder>(
                  getDeploymentSpec(),
                  getParentForChildren(),
                  isClean());
          deploymentSpec_ = null;
        }
        return deploymentSpecBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.BuildResult)
    }

    // @@protoc_insertion_point(class_scope:protos.BuildResult)
    private static final protos.DevopsOuterClass.BuildResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.DevopsOuterClass.BuildResult();
    }

    public static protos.DevopsOuterClass.BuildResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildResult>
        PARSER = new com.google.protobuf.AbstractParser<BuildResult>() {
      public BuildResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BuildResult(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BuildResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BuildResult> getParserForType() {
      return PARSER;
    }

    public protos.DevopsOuterClass.BuildResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Secret_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_Secret_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_BuildResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protos_BuildResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014devops.proto\022\006protos\032\017chaincode.proto\032" +
      "\017openchain.proto\"0\n\006Secret\022\020\n\010enrollId\030\001" +
      " \001(\t\022\024\n\014enrollSecret\030\002 \001(\t\"\272\001\n\013BuildResu" +
      "lt\022.\n\006status\030\001 \001(\0162\036.protos.BuildResult." +
      "StatusCode\022\013\n\003msg\030\002 \001(\t\0227\n\016deploymentSpe" +
      "c\030\003 \001(\0132\037.protos.ChaincodeDeploymentSpec" +
      "\"5\n\nStatusCode\022\r\n\tUNDEFINED\020\000\022\013\n\007SUCCESS" +
      "\020\001\022\013\n\007FAILURE\020\0022\271\002\n\006Devops\022+\n\005Login\022\016.pr" +
      "otos.Secret\032\020.protos.Response\"\000\022A\n\005Build" +
      "\022\025.protos.ChaincodeSpec\032\037.protos.Chainco",
      "deDeploymentSpec\"\000\022B\n\006Deploy\022\025.protos.Ch" +
      "aincodeSpec\032\037.protos.ChaincodeDeployment" +
      "Spec\"\000\022=\n\006Invoke\022\037.protos.ChaincodeInvoc" +
      "ationSpec\032\020.protos.Response\"\000\022<\n\005Query\022\037" +
      ".protos.ChaincodeInvocationSpec\032\020.protos" +
      ".Response\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protos.Chaincode.getDescriptor(),
          protos.Openchain.getDescriptor(),
        }, assigner);
    internal_static_protos_Secret_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_Secret_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_Secret_descriptor,
        new String[] { "EnrollId", "EnrollSecret", });
    internal_static_protos_BuildResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_BuildResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protos_BuildResult_descriptor,
        new String[] { "Status", "Msg", "DeploymentSpec", });
    protos.Chaincode.getDescriptor();
    protos.Openchain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
